{{- if .Values.gateway.enabled }}
{{- if .Values.gateway.create }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: {{ include "aether.name" . }}
  labels: {{- include "aether.labels" . | nindent 4 }}
spec:
  gatewayClassName: {{ .Values.gateway.className | quote }}
  listeners:
    - name: https
      hostname: {{ .Values.gateway.hostname | quote }}
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: {{ .Values.gateway.tlsSecretName | quote }}
      allowedRoutes:
        namespaces:
          from: Same
---
{{- end }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: {{ include "aether.name" . }}
  labels: {{- include "aether.labels" . | nindent 4 }}
spec:
  parentRefs:
    {{- if .Values.gateway.create }}
    - name: {{ include "aether.name" . }}
      sectionName: https
    {{- else }}
    {{- toYaml .Values.gateway.parentRefs | nindent 4 }}
    {{- end }}
  hostnames: [{{ .Values.gateway.hostname | quote }}]
  rules:
    - matches:
        - path: {type: PathPrefix, value: /}
      backendRefs:
        - name: {{ include "aether.name" . }}
          port: 8080
{{- end }}
