{{- if .Values.createTenantNamespaces }}
{{- range .Values.tenants }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .namespace | quote }}
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app.kubernetes.io/managed-by: {{ $.Release.Service | quote }}
    aether.dev/tenant: {{ .tenantId | quote }}
{{- end }}
{{- end }}
