apiVersion: v1
kind: Service
metadata:
  name: aether-headless
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: aether-runtime
  ports:
    - name: http
      port: 8080
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: aether
spec:
  selector:
    app.kubernetes.io/name: aether-runtime
  ports:
    - name: http
      port: 8080
      targetPort: http
