apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aether-acme
resources:
  - ../workspace
  - s3-egress.yaml
patches:
  - target:
      kind: Namespace
      name: aether
    patch: |-
      - op: replace
        path: /metadata/name
        value: aether-acme
  - path: statefulset.yaml
images:
  - name: registry.example.com/aether/workspace
    newTag: "0.3.0-acme"
